### ISSUE TITLE
Update 1.2.0!

### ISSUE THREAD

**Issue by matcracker** [matcracker/PocketMine-ManagerServers-Java#6]
New update-list for the software! Read below, a lot of amazing things will be added!
- [x] Software Updater
- [x] Plugin creator and manager (Create PocketMine plugins easily!)
  - [x] Add plugin.yml
  - [x] Add basic structure of class
  - [x] Supports imports
  - [x] Supports config.yml
  - [x] Supports events
    - \- [x] Blocks
    - \- [x] Entities
    - \- [x] Players
    - \- [x] Inventories
    - \- [x] Levels
  - [x] Support commands
  - [x] Custom code
  - [x] Improve menu structure
- [ ] Worlds Converter
  - [ ] Anvil to MCRegion
  - [ ] LevelDB to Anvil
  - [ ] MCRegion to Anvil

**Comment by Mattia990** [comment]
Very very good matcracker, i think is the best update ever!

**Comment by matcracker** [comment]
Yes, very useful for people that do plugins :+1:

**Comment by h1rule** [comment]
Is there a compiled version available for download?

**Comment by matcracker** [comment]
About 1.2?

**Comment by h1rule** [comment]
Yep. I dont know how to compile the 1.2 source :( - Theres no tutorial for it in the wiki.

**Comment by matcracker** [comment]
Quickly added in the wiki, thank you for letting me know!
Watch here: https://github.com/matcracker/PocketMine-ManagerServers/wiki/Install

**Comment by h1rule** [comment]
Thank you man <3

**Comment by matcracker** [comment]
If you have problems with compilation just ask me and I give you a compiled version.
When I finish commands part I'll release a first alpha of 1.2.0 ;)

**Comment by h1rule** [comment]
I have absolutley no idea with that App :d
Can you give me a compiled version? :D

**Comment by matcracker** [comment]
This version has some bugs. I suggest you to download the 1.1 for 99,999999% bugs free :)

**Comment by h1rule** [comment]
thanks!

Edit:

:(

=========================<PocketMine Manager Servers>===========================
------------------------------<pm.title.download>-------------------------------
File not found!
Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.BufferedReader.<init>(BufferedReader.java:101)
        at java.io.BufferedReader.<init>(BufferedReader.java:116)
        at com.matcracker.PMManagerServers.utility.Utility.readStringData(Utility.java:309)
        at com.matcracker.PMManagerServers.API.StatusAPI.getStatus(StatusAPI.java:57)
        at com.matcracker.PMManagerServers.installer.Downloader.downloaderMenu(Downloader.java:45)
        at com.matcracker.PMManagerServers.installer.ManagerInstaller.managerInstallerMenu(ManagerInstaller.java:76)
        at com.matcracker.PMManagerServers.PMMS.mainMenu(PMMS.java:116)
        at com.matcracker.PMManagerServers.PMMS.main(PMMS.java:68)

**Comment by matcracker** [comment]
Oh I forgot to give you languages... xD
And.. are you using a server OS?

**Comment by h1rule** [comment]
yes, i did -server

**Comment by matcracker** [comment]
Try now :) [PocketMine-ManagerServers_v1.2_prealpha.zip](https://github.com/matcracker/PocketMine-ManagerServers/files/414232/PocketMine-ManagerServers_v1.2_prealpha.zip)
Edit: delete all folders/file of previous installation

**Comment by matcracker** [comment]
If have other problems, you can use this chat :) https://gitter.im/matcracker/PocketMine-ManagerServers
